name: EAS Build
on:
  workflow_dispatch:
  push:
    branches:
      - staging
      - develop #TODO remove when done
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm

      - name: Install AWS cli
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update

      - name: Configure AWS cli credentials
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID --profile default  
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY --profile default  
          aws configure set default.region $AWS_REGION

      - name: Install AWS Amplify cli
        run: |
          npm install -g --unsafe-perm @aws-amplify/cli@latest
          echo "amplify version $(amplify --version)"

      - name: Initialize backend environment
        run: ./.github/scripts/amplify-init.sh staging

      - name: Push backend changes
        run: amplify push -yes
      - uses: stefanzweifel/git-auto-commit-action@v4

  build-ios:
    name: Install and build ios app (Preview)
    needs: deploy-backend
    uses: ./.github/workflows/eas-build.yaml
    secrets: inherit
    with:
      PLATFORM: ios
      PROFILE: preview
  build-android:
    name: Install and build android app (Preview)
    needs: deploy-backend
    uses: ./.github/workflows/eas-build.yaml
    secrets: inherit
    with:
      PLATFORM: android
      PROFILE: preview
